>>> 'Pkg.add("CauseMap")' log
INFO: Cloning cache of CauseMap from https://github.com/cyrusmaher/CauseMap.jl.git
INFO: Installing BinDeps v0.8.8
INFO: Installing CauseMap v0.0.3
INFO: Installing Conda v0.7.1
INFO: Installing MacroTools v0.4.0
INFO: Installing PyCall v1.16.1
INFO: Installing SHA v0.5.7
INFO: Installing URIParser v0.3.1
INFO: Installing VersionParsing v1.1.0
INFO: Building Conda
INFO: Building PyCall
Info: Using the Python distribution in the Conda package by default.
To use a different Python version, set ENV["PYTHON"]="pythoncommand" and re-run Pkg.build("PyCall").
Solving environment: ...working... done

# All requested packages already installed.

Info: PyCall is using /home/vagrant/.julia/v0.6/Conda/deps/usr/bin/python (Python 2.7.14) at /home/vagrant/.julia/v0.6/Conda/deps/usr/bin/python, libpython = /home/vagrant/.julia/v0.6/Conda/deps/usr/lib/libpython2.7
Info: /home/vagrant/.julia/v0.6/PyCall/deps/deps.jl has not changed
Info: /home/vagrant/.julia/v0.6/PyCall/deps/PYTHON has not changed
INFO: Package database updated
INFO: METADATA is out-of-date â€” you may not have the latest version of CauseMap
INFO: Use `Pkg.update()` to get the latest versions of your packages

>>> 'Pkg.test("CauseMap")' log
Julia Version 0.6.2
Commit d386e40c17 (2017-12-13 18:08 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz
  WORD_SIZE: 64
           Ubuntu 14.04.5 LTS
  uname: Linux 3.13.0-143-generic #192-Ubuntu SMP Tue Feb 27 10:45:36 UTC 2018 x86_64 x86_64
Memory: 2.939197540283203 GB (728.109375 MB free)
Uptime: 31928.0 sec
Load Avg:  1.0478515625  1.0146484375  0.96533203125
Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz: 
       speed         user         nice          sys         idle          irq
#1  3507 MHz    1831181 s       5750 s     133150 s     785488 s         26 s
#2  3507 MHz     378144 s       1392 s      51937 s    2710250 s          0 s

  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)
Environment:
  TERM = vt100
  LD_LIBRARY_PATH = :/usr/local/lib/
  PATH = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/vagrant/julia/bin/
  JAVA_HOME = /usr/lib/jvm/java-8-openjdk-amd64
  HOME = /home/vagrant

Package Directory: /home/vagrant/.julia/v0.6
2 required packages:
 - CauseMap                      0.0.3
 - JSON                          0.17.2
9 additional packages:
 - BinDeps                       0.8.8
 - Compat                        0.64.0
 - Conda                         0.7.1
 - MacroTools                    0.4.0
 - Nullables                     0.0.5
 - PyCall                        1.16.1
 - SHA                           0.5.7
 - URIParser                     0.3.1
 - VersionParsing                1.1.0
INFO: Testing CauseMap
ERROR: LoadError: LoadError: LoadError: LoadError: UndefVarError: ASCIIString not defined
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:576
 [2] include(::String) at ./sysimg.jl:14
 [3] include_from_node1(::String) at ./loading.jl:576
while loading /home/vagrant/.julia/v0.6/CauseMap/src/plotting.jl, in expression starting on line 1
while loading /home/vagrant/.julia/v0.6/CauseMap/src/CauseMap.jl, in expression starting on line 5
while loading /home/vagrant/.julia/v0.6/CauseMap/test/testplotting.jl, in expression starting on line 1
while loading /home/vagrant/.julia/v0.6/CauseMap/test/runtests.jl, in expression starting on line 1
==============================[ ERROR: CauseMap ]===============================

failed process: Process(`/home/vagrant/julia/bin/julia -Cx86-64 -J/home/vagrant/julia/lib/julia/sys.so --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=no --compilecache=yes /home/vagrant/.julia/v0.6/CauseMap/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
ERROR: CauseMap had test errors

>>> End of log
