>>> 'Pkg.add("CVXOPT")' log
INFO: Cloning cache of CVXOPT from https://github.com/cvxopt/CVXOPT.jl.git
INFO: Installing BinDeps v0.8.6
INFO: Installing CVXOPT v0.2.0
INFO: Installing Conda v0.7.1
INFO: Installing MacroTools v0.4.0
INFO: Installing PyCall v1.15.0
INFO: Installing SHA v0.5.6
INFO: Installing URIParser v0.3.0
INFO: Building Conda
INFO: Building PyCall
INFO: Using the Python distribution in the Conda package by default.
To use a different Python version, set ENV["PYTHON"]="pythoncommand" and re-run Pkg.build("PyCall").
Fetching package metadata .........
CondaHTTPError: HTTP 504 GATEWAY TIME-OUT for url <https://repo.continuum.io/pkgs/r/linux-64/repodata.json.bz2>
Elapsed: 00:10.022953
CF-RAY: 3e5d22fedef55a6e-BOS

An remote server error occurred when trying to retrieve this URL.

A 500-type error (e.g. 500, 501, 502, 503, etc.) indicates the server failed to
fulfill a valid request.  The problem may be spurious, and will resolve itself if you
try your request again.  If the problem persists, consider notifying the maintainer
of the remote server.


===============================[ ERROR: PyCall ]================================

LoadError: failed process: Process(setenv(`/home/vagrant/.julia/v0.6/Conda/deps/usr/bin/conda install -y numpy`,String["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/vagrant/julia/bin/", "PWD=/vagrant/0.6AF", "SHELL=/bin/bash", "SSH_CONNECTION=10.0.2.2 60054 10.0.2.15 22", "LD_LIBRARY_PATH=:/usr/local/lib/", "CONDARC=/home/vagrant/.julia/v0.6/Conda/deps/usr/condarc-julia.yml", "MAIL=/var/mail/vagrant", "LANG=en_US.UTF-8", "SHLVL=3", "LOGNAME=vagrant", "XDG_RUNTIME_DIR=/run/user/1000", "XDG_SESSION_ID=3", "CONDA_PREFIX=/home/vagrant/.julia/v0.6/Conda/deps/usr", "OLDPWD=/home/vagrant", "SSH_CLIENT=10.0.2.2 60054 22", "_=/usr/bin/timeout", "CONDA_DEFAULT_ENV=/home/vagrant/.julia/v0.6/Conda/deps/usr", "USER=vagrant", "TERM=vt100", "HOME=/home/vagrant", "OPENBLAS_MAIN_FREE=1", "JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64"]), ProcessExited(1)) [1]
while loading /home/vagrant/.julia/v0.6/PyCall/deps/build.jl, in expression starting on line 255

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: PyCall had build errors.

 - packages with build errors remain installed in /home/vagrant/.julia/v0.6
 - build the package(s) and all dependencies with `Pkg.build("PyCall")`
 - build a single package by running its `deps/build.jl` script

================================================================================
INFO: Package database updated
INFO: METADATA is out-of-date â€” you may not have the latest version of CVXOPT
INFO: Use `Pkg.update()` to get the latest versions of your packages

>>> 'Pkg.test("CVXOPT")' log
Julia Version 0.6.2
Commit d386e40c17 (2017-12-13 18:08 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz
  WORD_SIZE: 64
           Ubuntu 14.04.5 LTS
  uname: Linux 3.13.0-135-generic #184-Ubuntu SMP Wed Oct 18 11:55:51 UTC 2017 x86_64 x86_64
Memory: 2.93927001953125 GB (707.3359375 MB free)
Uptime: 46174.0 sec
Load Avg:  0.6953125  0.8447265625  1.06982421875
Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz: 
       speed         user         nice          sys         idle          irq
#1  3499 MHz    2968045 s       5852 s     138021 s     833926 s         29 s
#2  3499 MHz     797419 s        466 s      72311 s    3663271 s          0 s

  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)
Environment:
  TERM = vt100
  LD_LIBRARY_PATH = :/usr/local/lib/
  PATH = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/vagrant/julia/bin/
  JAVA_HOME = /usr/lib/jvm/java-8-openjdk-amd64
  HOME = /home/vagrant

Package Directory: /home/vagrant/.julia/v0.6
2 required packages:
 - CVXOPT                        0.2.0
 - JSON                          0.16.4
8 additional packages:
 - BinDeps                       0.8.6
 - Compat                        0.49.0
 - Conda                         0.7.1
 - MacroTools                    0.4.0
 - Nullables                     0.0.3
 - PyCall                        1.15.0
 - SHA                           0.5.6
 - URIParser                     0.3.0
INFO: Testing CVXOPT
ERROR: LoadError: LoadError: PyCall not properly installed. Please run Pkg.build("PyCall")
Stacktrace:
 [1] macro expansion at /home/vagrant/.julia/v0.6/PyCall/src/startup.jl:44 [inlined]
 [2] anonymous at ./<missing>:?
 [3] include_from_node1(::String) at ./loading.jl:576
 [4] include(::String) at ./sysimg.jl:14
 [5] include_from_node1(::String) at ./loading.jl:576
 [6] include(::String) at ./sysimg.jl:14
 [7] anonymous at ./<missing>:2
while loading /home/vagrant/.julia/v0.6/PyCall/src/startup.jl, in expression starting on line 41
while loading /home/vagrant/.julia/v0.6/PyCall/src/PyCall.jl, in expression starting on line 39
ERROR: LoadError: LoadError: Failed to precompile PyCall to /home/vagrant/.julia/lib/v0.6/PyCall.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:710
 [2] _require(::Symbol) at ./loading.jl:463
 [3] require(::Symbol) at ./loading.jl:405
 [4] include_from_node1(::String) at ./loading.jl:576
while loading /home/vagrant/.julia/v0.6/CVXOPT/src/CVXOPT.jl, in expression starting on line 2
while loading /home/vagrant/.julia/v0.6/CVXOPT/test/runtests.jl, in expression starting on line 1
===============================[ ERROR: CVXOPT ]================================

failed process: Process(`/home/vagrant/julia/bin/julia -Cx86-64 -J/home/vagrant/julia/lib/julia/sys.so --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=no --compilecache=yes /home/vagrant/.julia/v0.6/CVXOPT/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
ERROR: CVXOPT had test errors

>>> End of log
