>>> 'Pkg.add("DataFrames")' log
INFO: Installing ArrayViews v0.4.6
INFO: Installing DataArrays v0.2.1
INFO: Installing DataFrames v0.5.8
INFO: Installing GZip v0.2.13
INFO: Installing Reexport v0.0.1
INFO: Installing SortingAlgorithms v0.0.1
INFO: Installing StatsBase v0.6.5
INFO: Package database updated

>>> 'using DataFrames' log
Julia Version 0.4.0-dev+856
Commit 46c7bbf (2014-09-30 04:44 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

>>> test log
ERROR: "Tests failed"
 in include at ./boot.jl:245
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:285
 in _start at ./client.jl:354
 in _start_3B_3624 at /home/idunning/julia04/usr/bin/../lib/julia/sys.so
while loading /home/idunning/pkgtest/.julia/v0.4/DataFrames/test/runtests.jl, in expression starting on line 49
Running tests:
	[1m[32mPASSED[0m: utils.jl
	[1m[32mPASSED[0m: data.jl
	[1m[32mPASSED[0m: index.jl
	[1m[31mFAILED[0m: dataframe.jl
`getindex` has no method matching getindex(::DataFrame, ::Array{Any,1}, ::UnitRange{Int64})
 in anonymous at no file:42
 in include at ./boot.jl:245
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:285
 in _start at ./client.jl:354
 in _start_3B_3624 at /home/idunning/julia04/usr/bin/../lib/julia/sys.so
while loading /home/idunning/pkgtest/.julia/v0.4/DataFrames/test/dataframe.jl, in expression starting on line 49
	[1m[32mPASSED[0m: io.jl
	[1m[32mPASSED[0m: constructors.jl
	[1m[32mPASSED[0m: conversions.jl
	[1m[31mFAILED[0m: RDA.jl
test error in expression: isequal(DataFrame((read_rda("$testdir/data/RDA/NAs.rda"))["df"]),df)
InexactError()
 in copy! at abstractarray.jl:149
 in convert at array.jl:220
 in data at /home/idunning/pkgtest/.julia/v0.4/DataFrames/src/RDA.jl:298
 in anonymous at /home/idunning/pkgtest/.julia/v0.4/DataFrames/src/RDA.jl:309
 in map at ./base.jl:184
 in DataFrame at /home/idunning/pkgtest/.julia/v0.4/DataFrames/src/RDA.jl:309
 in anonymous at test.jl:85
 in do_test at test.jl:47
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in anonymous at no file:34
 in include at ./boot.jl:245
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:285
 in _start at ./client.jl:354
 in _start_3B_3624 at /home/idunning/julia04/usr/bin/../lib/julia/sys.so
while loading /home/idunning/pkgtest/.julia/v0.4/DataFrames/test/RDA.jl, in expression starting on line 36
	[1m[32mPASSED[0m: sort.jl
	[1m[32mPASSED[0m: grouping.jl
	[1m[32mPASSED[0m: join.jl
	[1m[32mPASSED[0m: vcat.jl
	[1m[32mPASSED[0m: iteration.jl
	[1m[32mPASSED[0m: duplicates.jl
	[1m[32mPASSED[0m: show.jl


INFO: Testing DataFrames
=============================[ ERROR: DataFrames ]==============================

failed process: Process(`/home/idunning/julia04/usr/bin/julia /home/idunning/pkgtest/.julia/v0.4/DataFrames/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
INFO: No packages to install, update or remove
ERROR: DataFrames had test errors
 in error at error.jl:21
 in test at pkg/entry.jl:719
 in anonymous at pkg/dir.jl:28
 in cd at ./file.jl:20
 in cd at pkg/dir.jl:28
 in test at pkg.jl:68
 in process_options at ./client.jl:213
 in _start at ./client.jl:354
 in _start_3B_3624 at /home/idunning/julia04/usr/bin/../lib/julia/sys.so

>>> end of log
