>>> 'Pkg.add("DataFrames")' log
INFO: Installing ArrayViews v0.4.8
INFO: Installing DataArrays v0.2.5
INFO: Installing DataFrames v0.5.11
INFO: Installing GZip v0.2.13
INFO: Installing Reexport v0.0.2
INFO: Installing SortingAlgorithms v0.0.2
INFO: Installing StatsBase v0.6.8
INFO: Package database updated

>>> 'using DataFrames' log
Warning: could not import Base.evaluate into StatsBase
Julia Version 0.4.0-dev+1330
Commit 7fdc860 (2014-10-28 03:56 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

>>> test log
Warning: could not import Base.evaluate into StatsBase
ERROR: "Tests failed"
 in include at ./boot.jl:242
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:293
 in _start at ./client.jl:362
 in _start_3B_3769 at /home/idunning/julia04/usr/bin/../lib/julia/sys.so
while loading /home/idunning/pkgtest/.julia/v0.4/DataFrames/test/runtests.jl, in expression starting on line 49
Running tests:
	[1m[32mPASSED[0m: utils.jl
	[1m[32mPASSED[0m: data.jl
	[1m[32mPASSED[0m: index.jl
	[1m[31mFAILED[0m: dataframe.jl
type: invoke: expected Function, got Type{DataFrame}
 in anonymous at no file:42
 in include at ./boot.jl:242
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:293
 in _start at ./client.jl:362
 in _start_3B_3769 at /home/idunning/julia04/usr/bin/../lib/julia/sys.so
while loading /home/idunning/pkgtest/.julia/v0.4/DataFrames/test/dataframe.jl, in expression starting on line 136
	[1m[31mFAILED[0m: io.jl
Failed to read /home/idunning/pkgtest/.julia/v0.4/DataFrames/test/data/blanklines/blanklines.csv

 in anonymous at no file:42
 in include at ./boot.jl:242
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:293
 in _start at ./client.jl:362
 in _start_3B_3769 at /home/idunning/julia04/usr/bin/../lib/julia/sys.so
while loading /home/idunning/pkgtest/.julia/v0.4/DataFrames/test/io.jl, in expression starting on line 25
	[1m[32mPASSED[0m: formula.jl
	[1m[32mPASSED[0m: constructors.jl
	[1m[32mPASSED[0m: conversions.jl
	[1m[32mPASSED[0m: RDA.jl
	[1m[32mPASSED[0m: sort.jl
	[1m[32mPASSED[0m: grouping.jl
	[1m[32mPASSED[0m: join.jl
	[1m[32mPASSED[0m: vcat.jl
	[1m[32mPASSED[0m: iteration.jl
	[1m[32mPASSED[0m: duplicates.jl
	[1m[32mPASSED[0m: show.jl


INFO: Testing DataFrames
=============================[ ERROR: DataFrames ]==============================

failed process: Process(`/home/idunning/julia04/usr/bin/julia /home/idunning/pkgtest/.julia/v0.4/DataFrames/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
INFO: No packages to install, update or remove
ERROR: DataFrames had test errors
 in error at error.jl:21
 in test at pkg/entry.jl:719
 in anonymous at pkg/dir.jl:28
 in cd at ./file.jl:20
 in cd at pkg/dir.jl:28
 in test at pkg.jl:68
 in process_options at ./client.jl:221
 in _start at ./client.jl:362
 in _start_3B_3769 at /home/idunning/julia04/usr/bin/../lib/julia/sys.so

>>> end of log
