>>> 'Pkg.add("PyAMG")' log
INFO: Installing BinDeps v0.4.7
INFO: Installing Conda v0.5.3
INFO: Installing MacroTools v0.3.7
INFO: Installing PyAMG v0.0.9
INFO: Installing PyCall v1.11.1
INFO: Installing SHA v0.3.3
INFO: Installing URIParser v0.1.8
INFO: Building Conda
INFO: Building PyCall
INFO: Using the Python distribution in the Conda package by default.
To use a different Python version, set ENV["PYTHON"]="pythoncommand" and re-run Pkg.build("PyCall").
Fetching package metadata .........
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /home/vagrant/.julia/v0.4/Conda/deps/usr:
#
numpy                     1.13.0                   py27_0  
INFO: PyCall is using /home/vagrant/.julia/v0.4/Conda/deps/usr/bin/python (Python 2.7.13) at /home/vagrant/.julia/v0.4/Conda/deps/usr/bin/python, libpython = /home/vagrant/.julia/v0.4/Conda/deps/usr/lib/libpython2.7
INFO: /home/vagrant/.julia/v0.4/PyCall/deps/deps.jl has not changed
INFO: /home/vagrant/.julia/v0.4/PyCall/deps/PYTHON has not changed
INFO: Package database updated
INFO: METADATA is out-of-date â€” you may not have the latest version of PyAMG
INFO: Use `Pkg.update()` to get the latest versions of your packages

>>> 'Pkg.test("PyAMG")' log
Julia Version 0.4.7
Commit ae26b25 (2016-09-18 16:17 UTC)
Platform Info:
  System: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz
  WORD_SIZE: 64
           Ubuntu 14.04.5 LTS
  uname: Linux 3.13.0-121-generic #170-Ubuntu SMP Wed Jun 14 09:04:33 UTC 2017 x86_64 x86_64
Memory: 2.9392738342285156 GB (520.3671875 MB free)
Uptime: 24265.0 sec
Load Avg:  1.19873046875  1.0029296875  0.93115234375
Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz: 
       speed         user         nice          sys         idle          irq
#1  3499 MHz    1131078 s       6296 s      93517 s     938190 s         18 s
#2  3499 MHz     786679 s         84 s      78952 s    1470953 s          0 s

  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
Environment:
  TERM = vt100
  LD_LIBRARY_PATH = :/usr/local/lib/
  PATH = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/vagrant/julia/bin/
  JAVA_HOME = /usr/lib/jvm/java-8-openjdk-amd64
  HOME = /home/vagrant

Package Directory: /home/vagrant/.julia/v0.4
2 required packages:
 - JSON                          0.9.1
 - PyAMG                         0.0.9
7 additional packages:
 - BinDeps                       0.4.7
 - Compat                        0.26.0
 - Conda                         0.5.3
 - MacroTools                    0.3.7
 - PyCall                        1.11.1
 - SHA                           0.3.3
 - URIParser                     0.1.8
INFO: Computing test dependencies for PyAMG...
INFO: Cloning cache of IterativeSolvers from git://github.com/JuliaMath/IterativeSolvers.jl.git
INFO: Installing IterativeSolvers v0.2.2
INFO: Testing PyAMG
=================================================
Test 1: Julia `\` vs PyAMG Blackbox `solve` (2D) Laplacian
 \ :   0.340886 seconds (393.72 k allocations: 26.655 MB, 1.61% gc time)
PyAMG-Warmup: /home/vagrant/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/pyamg/strength.py:533: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if B == 'ones':
ERROR: LoadError: PyError (:PyObject_Call) <type 'exceptions.TypeError'>
TypeError('Failed generating smoothed_aggregation_solver',)
  File "/home/vagrant/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/pyamg/blackbox.py", line 284, in solve
    existing_solver = solver(A, config)
  File "/home/vagrant/.julia/v0.4/Conda/deps/usr/lib/python2.7/site-packages/pyamg/blackbox.py", line 215, in solver
    raise TypeError('Failed generating smoothed_aggregation_solver')

 [inlined code] from /home/vagrant/.julia/v0.4/PyCall/src/exception.jl:81
 in _pycall at /home/vagrant/.julia/v0.4/PyCall/src/PyCall.jl:556
 in pycall at /home/vagrant/.julia/v0.4/PyCall/src/PyCall.jl:573
 in call at /home/vagrant/.julia/v0.4/PyCall/src/PyCall.jl:576
 in solve at /home/vagrant/.julia/v0.4/PyAMG/src/PyAMG.jl:128
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:333
 in process_options at ./client.jl:280
 in _start at ./client.jl:378
while loading /home/vagrant/.julia/v0.4/PyAMG/test/runtests.jl, in expression starting on line 155
================================[ ERROR: PyAMG ]================================

failed process: Process(`/home/vagrant/julia/bin/julia --check-bounds=yes --code-coverage=none --color=no /home/vagrant/.julia/v0.4/PyAMG/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
INFO: Removing IterativeSolvers v0.2.2
ERROR: PyAMG had test errors
 in error at ./error.jl:21
 in test at pkg/entry.jl:803
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in test at pkg.jl:71
 in process_options at ./client.jl:257
 in _start at ./client.jl:378

>>> End of log
