>>> 'Pkg.add("PyCall")' log
INFO: Installing PyCall v0.7.3
INFO: Package database updated
INFO: METADATA is out-of-date a you may not have the latest version of PyCall
INFO: Use `Pkg.update()` to get the latest versions of your packages

>>> 'using PyCall' log
Julia Version 0.4.0-dev+2736
Commit a3485dd (2015-01-16 03:36 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

>>> test log

WARNING: deprecated syntax "[a=>b, ...]" at /home/idunning/pkgtest/.julia/v0.4/PyCall/test/runtests.jl:23.
Use "Dict(a=>b, ...)" instead.

WARNING: deprecated syntax "[a=>b, ...]" at /home/idunning/pkgtest/.julia/v0.4/PyCall/test/runtests.jl:39.
Use "Dict(a=>b, ...)" instead.

WARNING: deprecated syntax "[a=>b, ...]" at /home/idunning/pkgtest/.julia/v0.4/PyCall/test/runtests.jl:39.
Use "Dict(a=>b, ...)" instead.

WARNING: deprecated syntax "[a=>b, ...]" at /home/idunning/pkgtest/.julia/v0.4/PyCall/test/runtests.jl:41.
Use "Dict(a=>b, ...)" instead.

ERROR: LoadError: PyError (:PyObject_Call) <class 'TypeError'>
TypeError('an integer is required',)

 in pyerr_check at /home/idunning/pkgtest/.julia/v0.4/PyCall/src/exception.jl:58
 in pycall at /home/idunning/pkgtest/.julia/v0.4/PyCall/src/PyCall.jl:91
 in fn at /home/idunning/pkgtest/.julia/v0.4/PyCall/src/conversions.jl:181
 in anonymous at no file:112
 in include at ./boot.jl:248
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:312
 in _start at ./client.jl:396
while loading /home/idunning/pkgtest/.julia/v0.4/PyCall/test/runtests.jl, in expression starting on line 107

INFO: Testing PyCall
===============================[ ERROR: PyCall ]================================

failed process: Process(`/home/idunning/julia04/usr/bin/julia --check-bounds=yes --code-coverage=none --color=no /home/idunning/pkgtest/.julia/v0.4/PyCall/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
INFO: No packages to install, update or remove
ERROR: PyCall had test errors
 in error at error.jl:19
 in test at pkg/entry.jl:717
 in anonymous at pkg/dir.jl:28
 in cd at ./file.jl:20
 in cd at pkg/dir.jl:28
 in test at pkg.jl:68
 in process_options at ./client.jl:234
 in _start at ./client.jl:396

>>> end of log
