Tests exist, ran 'julia runtests.jl', failed!
INFO: Installing PyCall v0.4.5
INFO: REQUIRE updated.
ERROR: test failed: :((collect(PyObject([1,3,5]))==[1,3,5]))
 in error at error.jl:21
 in default_handler at test.jl:19
 in do_test at test.jl:39
 in include at boot.jl:238
at /home/idunning/pkgtest/.julia/v0.2/PyCall/test/runtests.jl:66
INFO: REQUIRE updated.
