>>> 'Pkg.add("RemoteFiles")' log
INFO: Cloning cache of RemoteFiles from https://github.com/helgee/RemoteFiles.jl.git
INFO: Installing RemoteFiles v0.1.0
INFO: Installing URIParser v0.3.1
INFO: Building RemoteFiles
INFO: Package database updated

>>> 'Pkg.test("RemoteFiles")' log
Julia Version 0.6.2
Commit d386e40c17 (2017-12-13 18:08 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz
  WORD_SIZE: 64
           Ubuntu 14.04.5 LTS
  uname: Linux 3.13.0-143-generic #192-Ubuntu SMP Tue Feb 27 10:45:36 UTC 2018 x86_64 x86_64
Memory: 2.939197540283203 GB (710.2890625 MB free)
Uptime: 40938.0 sec
Load Avg:  1.0029296875  0.99462890625  0.9599609375
Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz: 
       speed         user         nice          sys         idle          irq
#1  3500 MHz    2303551 s       1362 s     167756 s    1053122 s         33 s
#2  3500 MHz     552450 s       5235 s      65933 s    3395068 s          0 s

  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)
Environment:
  TERM = vt100
  LD_LIBRARY_PATH = :/usr/local/lib/
  PATH = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/vagrant/julia/bin/
  JAVA_HOME = /usr/lib/jvm/java-8-openjdk-amd64
  HOME = /home/vagrant

Package Directory: /home/vagrant/.julia/v0.6
2 required packages:
 - JSON                          0.17.2
 - RemoteFiles                   0.1.0
3 additional packages:
 - Compat                        0.64.0
 - Nullables                     0.0.5
 - URIParser                     0.3.1
INFO: Testing RemoteFiles
WARNING: replacing module RemoteFiles.
RemoteFile: Error During Test
  Got an exception of type ErrorException outside of a @test
  Download of 'https://httpbin.org/image/png' failed after 3 retries.
  Stacktrace:
   [1] #download#37(::Bool, ::Bool, ::Bool, ::Function, ::RemoteFiles.RemoteFile) at /home/vagrant/.julia/v0.6/RemoteFiles/src/download.jl:91
   [2] (::Base.#kw##download)(::Array{Any,1}, ::Base.#download, ::RemoteFiles.RemoteFile) at ./<missing>:0
   [3] redirect_stderr(::##2#4{##5#8}, ::IOStream) at ./stream.jl:1086
   [4] open(::##1#3{##5#8}, ::String, ::String) at ./iostream.jl:152
   [5] capture_stderr(::##5#8) at /home/vagrant/.julia/v0.6/RemoteFiles/test/runtests.jl:10
   [6] macro expansion at /home/vagrant/.julia/v0.6/RemoteFiles/test/runtests.jl:30 [inlined]
   [7] macro expansion at ./test.jl:860 [inlined]
   [8] macro expansion at /home/vagrant/.julia/v0.6/RemoteFiles/test/runtests.jl:23 [inlined]
   [9] macro expansion at ./test.jl:860 [inlined]
   [10] anonymous at ./<missing>:?
   [11] include_from_node1(::String) at ./loading.jl:576
   [12] include(::String) at ./sysimg.jl:14
   [13] process_options(::Base.JLOptions) at ./client.jl:305
   [14] _start() at ./client.jl:371
INFO: Downloading file 'image1.png' from 'https://httpbin.org/image/png'.
INFO: Downloading file 'image2.png' from 'https://httpbin.org/image/png'.
WARNING: Download failed with error: failed process: Process(`curl -s -o /tmp/juliad934Tt -L https://httpbin.org/image/png`, ProcessExited(7)) [7]
INFO: Retrying in 5 seconds.
WARNING: Download failed with error: failed process: Process(`curl -s -o /tmp/juliauwsH9K -L https://httpbin.org/image/png`, ProcessExited(7)) [7]
INFO: Retrying in 5 seconds.
WARNING: Download failed with error: failed process: Process(`curl -s -o /tmp/juliauwsH9K -L https://httpbin.org/image/png`, ProcessExited(7)) [7]
INFO: Retrying in 5 seconds.
WARNING: Download failed with error: failed process: Process(`curl -s -o /tmp/juliad934Tt -L https://httpbin.org/image/png`, ProcessExited(7)) [7]
INFO: Retrying in 5 seconds.
WARNING: Download failed with error: failed process: Process(`curl -s -o /tmp/juliauwsH9K -L https://httpbin.org/image/png`, ProcessExited(7)) [7]
WARNING: Download failed with error: failed process: Process(`curl -s -o /tmp/juliad934Tt -L https://httpbin.org/image/png`, ProcessExited(7)) [7]
INFO: Retrying in 5 seconds.
INFO: Retrying in 5 seconds.
RemoteFileSets: Error During Test
  Got an exception of type CompositeException outside of a @test
  Download of 'https://httpbin.org/image/png' failed after 3 retries.
  #download#37(::Bool, ::Bool, ::Bool, ::Function, ::RemoteFiles.RemoteFile) at /home/vagrant/.julia/v0.6/RemoteFiles/src/download.jl:91
  (::Base.#kw##download)(::Array{Any,1}, ::Base.#download, ::RemoteFiles.RemoteFile) at ./<missing>:0
  (::RemoteFiles.##39#40{Bool,Bool})() at ./task.jl:335
  
  ...and 1 more exception(s).
  
  Stacktrace:
   [1] sync_end() at ./task.jl:287
   [2] macro expansion at ./task.jl:303 [inlined]
   [3] #download#38(::Bool, ::Bool, ::Bool, ::Function, ::RemoteFiles.RemoteFileSet) at /home/vagrant/.julia/v0.6/RemoteFiles/src/RemoteFiles.jl:227
   [4] macro expansion at /home/vagrant/.julia/v0.6/RemoteFiles/test/runtests.jl:95 [inlined]
   [5] macro expansion at ./test.jl:860 [inlined]
   [6] macro expansion at /home/vagrant/.julia/v0.6/RemoteFiles/test/runtests.jl:89 [inlined]
   [7] macro expansion at ./test.jl:860 [inlined]
   [8] anonymous at ./<missing>:?
   [9] include_from_node1(::String) at ./loading.jl:576
   [10] include(::String) at ./sysimg.jl:14
   [11] process_options(::Base.JLOptions) at ./client.jl:305
   [12] _start() at ./client.jl:371
Test Summary:    | Pass  Error  Total
RemoteFiles      |   26      2     28
  RemoteFile     |    2      1      3
  RemoteFileSets |           1      1
  Updates        |   24            24
ERROR: LoadError: Some tests did not pass: 26 passed, 0 failed, 2 errored, 0 broken.
while loading /home/vagrant/.julia/v0.6/RemoteFiles/test/runtests.jl, in expression starting on line 22
=============================[ ERROR: RemoteFiles ]=============================

failed process: Process(`/home/vagrant/julia/bin/julia -Cx86-64 -J/home/vagrant/julia/lib/julia/sys.so --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=no --compilecache=yes /home/vagrant/.julia/v0.6/RemoteFiles/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
ERROR: RemoteFiles had test errors

>>> End of log
