>>> 'Pkg.add("SGP4")' log
INFO: Cloning cache of Dates from https://github.com/quinnj/Dates.jl.git
INFO: Cloning cache of SGP4 from https://github.com/crbinz/SGP4.jl.git
INFO: Installing BinDeps v0.4.7
INFO: Installing Conda v0.5.3
INFO: Installing Dates v0.4.4
INFO: Installing MacroTools v0.3.6
INFO: Installing PyCall v1.12.0
INFO: Installing SGP4 v0.3.0
INFO: Installing SHA v0.3.2
INFO: Installing URIParser v0.1.8
INFO: Building Conda
INFO: Building PyCall
INFO: Using the Python distribution in the Conda package by default.
To use a different Python version, set ENV["PYTHON"]="pythoncommand" and re-run Pkg.build("PyCall").
INFO: PyCall is using /home/vagrant/.julia/v0.6/Conda/deps/usr/bin/python (Python 2.7.13) at /home/vagrant/.julia/v0.6/Conda/deps/usr/bin/python, libpython = /home/vagrant/.julia/v0.6/Conda/deps/usr/lib/libpython2.7
INFO: /home/vagrant/.julia/v0.6/PyCall/deps/deps.jl has not changed
INFO: /home/vagrant/.julia/v0.6/PyCall/deps/PYTHON has not changed
INFO: Package database updated
INFO: METADATA is out-of-date â€” you may not have the latest version of SGP4
INFO: Use `Pkg.update()` to get the latest versions of your packages

>>> 'Pkg.test("SGP4")' log
Julia Version 0.6.0-pre.beta.314
Commit 7cd0324 (2017-04-24 22:37 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz
  WORD_SIZE: 64
           Ubuntu 14.04.5 LTS
  uname: Linux 3.13.0-117-generic #164-Ubuntu SMP Fri Apr 7 11:05:26 UTC 2017 x86_64 x86_64
Memory: 2.9392738342285156 GB (881.5078125 MB free)
Uptime: 57534.0 sec
Load Avg:  0.923828125  0.96923828125  0.94970703125
Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz: 
       speed         user         nice          sys         idle          irq
#1  3500 MHz    3544865 s       6248 s     144750 s    1148843 s         43 s
#2  3500 MHz     608184 s        100 s      69315 s    5000730 s          1 s

  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, haswell)
Environment:
  TERM = vt100
  LD_LIBRARY_PATH = :/usr/local/lib/
  PATH = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/vagrant/julia/bin/
  JAVA_HOME = /usr/lib/jvm/java-7-oracle
  HOME = /home/vagrant

Package Directory: /home/vagrant/.julia/v0.6
2 required packages:
 - JSON                          0.9.1
 - SGP4                          0.3.0
8 additional packages:
 - BinDeps                       0.4.7
 - Compat                        0.24.0
 - Conda                         0.5.3
 - Dates                         0.4.4
 - MacroTools                    0.3.6
 - PyCall                        1.12.0
 - SHA                           0.3.2
 - URIParser                     0.1.8
INFO: Testing SGP4
INFO: Installing sgp4.io via the Conda sgp4 package...
Warning: 'conda-forge' already in 'channels' list, moving to the top
Fetching package metadata ...

CondaHTTPError: HTTP 502 None
for url <None>

An remote server error occurred when trying to retrieve this URL.

A 500-type error (e.g. 500, 501, 502, 503, etc.) indicates the server failed to
fulfill a valid request.  The problem may be spurious, and will resolve itself if you
try your request again.  If the problem persists, consider notifying the maintainer
of the remote server.



ERROR: LoadError: InitError: failed process: Process(setenv(`/home/vagrant/.julia/v0.6/Conda/deps/usr/bin/conda install -y sgp4`,String["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/vagrant/julia/bin/", "PWD=/vagrant/0.6LZ", "SHELL=/bin/bash", "SSH_CONNECTION=10.0.2.2 33099 10.0.2.15 22", "LD_LIBRARY_PATH=:/usr/local/lib/", "CONDARC=/home/vagrant/.julia/v0.6/Conda/deps/usr/condarc-julia.yml", "MAIL=/var/mail/vagrant", "LANG=en_US.UTF-8", "SHLVL=4", "LOGNAME=vagrant", "XDG_RUNTIME_DIR=/run/user/1000", "XDG_SESSION_ID=3", "CONDA_PREFIX=/home/vagrant/.julia/v0.6/Conda/deps/usr", "SSH_CLIENT=10.0.2.2 33099 22", "_=/usr/bin/timeout", "CONDA_DEFAULT_ENV=/home/vagrant/.julia/v0.6/Conda/deps/usr", "USER=vagrant", "TERM=vt100", "HOME=/home/vagrant", "OPENBLAS_MAIN_FREE=1", "JAVA_HOME=/usr/lib/jvm/java-7-oracle"]), ProcessExited(1)) [1]
Stacktrace:
 [1] pipeline_error(::Base.Process) at ./process.jl:687
 [2] run(::Cmd) at ./process.jl:656
 [3] runconda(::Cmd, ::String) at /home/vagrant/.julia/v0.6/Conda/src/Conda.jl:131
 [4] pyimport_conda(::String, ::String, ::String) at /home/vagrant/.julia/v0.6/PyCall/src/PyCall.jl:482
 [5] __init__() at /home/vagrant/.julia/v0.6/SGP4/src/SGP4.jl:17
 [6] _include_from_serialized(::String) at ./loading.jl:157
 [7] _require_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:194
 [8] require(::Symbol) at ./loading.jl:461
 [9] include_from_node1(::String) at ./loading.jl:539
 [10] include(::String) at ./sysimg.jl:14
 [11] process_options(::Base.JLOptions) at ./client.jl:305
 [12] _start() at ./client.jl:371
during initialization of module SGP4
while loading /home/vagrant/.julia/v0.6/SGP4/test/runtests.jl, in expression starting on line 1
================================[ ERROR: SGP4 ]=================================

failed process: Process(`/home/vagrant/julia/bin/julia -Cx86-64 -J/home/vagrant/julia/lib/julia/sys.so --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=no --compilecache=yes /home/vagrant/.julia/v0.6/SGP4/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
ERROR: SGP4 had test errors

>>> End of log
