Tests exist, tried 'using SymPy', failed!
INFO: Installing PyCall v0.4.2
INFO: Installing SymPy v0.2.6
INFO: Package database updated
ERROR: PyError (PyImport_ImportModule) <class 'ImportError'>
ImportError("No module named 'sympy'",)

 in pyerr_check at /home/idunning/pkgtest/.julia/v0.3/PyCall/src/exception.jl:58
 in pyimport at /home/idunning/pkgtest/.julia/v0.3/PyCall/src/PyCall.jl:85
 in include at boot.jl:244
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:51
 in include at boot.jl:244
 in include_from_node1 at loading.jl:128
while loading /home/idunning/pkgtest/.julia/v0.3/SymPy/src/SymPy.jl, in expression starting on line 723
while loading /home/idunning/pkgtest/.julia/v0.3/.trash/SVM/testusing.jl, in expression starting on line 1
INFO: Package database updated
